config/routes.rb
Rails.application.routes.draw do
  resources :students, only: [:index, :show, :new, :create]
  resources :events
  resources :dishes
  resources :allergens
  resources :ingredients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allergen.rb
class Allergen < ApplicationRecord
  belongs_to :student
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :ingredients
  belongs_to :student
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :allergens
  belongs_to :dish
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :dishes
  has_many :allergens
  belongs_to :event
end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    binding.pry
    @students = Student.all
  end

  def new
    @student = Student.new
    render :new
  end

  def create
    @student = Student.new(name:params[:student][:name])
    @student.save
    render :index
end


end

app/helpers/allergen_helper.rb
module AllergenHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dish_helper.rb
module DishHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potluck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1> Welcome To The Octothorpes Potluck </h1>

<h2>Here are the students taking part:</h2>
<ul>
  <% @students.each do |student| %>
<li>
<%= link_to student.name, student_path(student) %>
</li>
</ul>
<% end %>

app/views/students/new.html.erb
<%= form_for @student do |f| %>
<%= f.label :name %>
<br />
<%= f.text_field :name %>

<%= f.submit %>
<% end %>